merging in backup control changes #155
NREL/OCHRE pull request #160
Opened 2024-12-09 21:36 UTC by kendallbaertlein

- [X] Reference the issue your PR is fixing
- [X] Assign at least 1 reviewer for your PR
- [ ] Test with run_dwelling.py or other script
- [X] Update documentation as appropriate
- [ ] Update changelog as appropriate

2024-12-10 20:14 UTC, jmaguire1 commented
For posterity, why we added the deadband weight: At least one major manufacturer shows that when you run with an ASHP in heating or cooling, they tend to be pretty lopsided in terms of maintaining the setpoint. I tried to make that change consistently throughout the code.

2024-12-18 17:00 UTC, jmaguire1 approved these changes
Looks good to me. Unless @mnblonsky has final comments, I'll merge this in later this week.

2024-12-18 17:00 UTC, jmaguire1 commented on ochre/Equipment/HVAC.py
> +                # elif self.end_use == 'HVAC Cooling':
Removed

2024-12-18 17:00 UTC, jmaguire1 commented on ochre/Equipment/HVAC.py
> +                    print(f"minimum setpoint change duration ({min_setpoint_change_duration} minutes) updated to comply with hard lockout interval ({hard_lockout} minutes)") #TODO: raise warning ?
Done

2024-12-23 21:00 UTC, mnblonsky commented
Is there a file or script to test the new functionality? I'd like to make sure it runs under a few conditions, e.g. 1 min vs 15 min resolution.

2024-12-31 21:30 UTC, mnblonsky requested changes

2024-12-31 21:45 UTC, mnblonsky commented
> Is there a file or script to test the new functionality? I'd like to make sure it runs under a few conditions, e.g. 1 min vs 15 min resolution.

I'll add a script or at least run a test before merging

2025-01-20 22:58 UTC, mnblonsky commented
> I'll add a script or at least run a test before merging

Tested with `run_dwelling`. I used `bldg0112631-up11.xml` with the first few hours of Jan 1, and ran a few tests changing the backup control input parameters. I had to shift the HVAC setpoint for 30 min or so a few times to check that all the lockouts were working, but it looks good.

2025-01-20 23:09 UTC, mnblonsky approved these changes

2025-01-20 23:11 UTC, merged